export enum SystemErrCode {
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  BODY_PARSING_FAILED = "BODY_PARSING_FAILED",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  ROUTE_ALREADY_REGISTERED = "ROUTE_ALREADY_REGISTERED",
  ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",
  INTERNAL_SERVER_ERR = "INTERNAL_SERVER_ERROR",
  WEBSOCKET_UPGRADE_FAILURE = "WEBSOCKET_UPGRADE_FAILURE",
  HEADERS_ALREADY_SENT = "HEADERS_ALREADY_SENT",
}
